version: '3'

services:
  postgres_test:
    image: postgres:16-alpine
    container_name: my_new_gear_postgres_test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_new_gear_test
    ports:
      - '5433:5432'
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  app_test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_new_gear_app_test
    environment:
      NODE_ENV: test
      DATABASE_URL: postgresql://postgres:postgres@postgres_test:5432/my_new_gear_test
      PORT: 3001
      JWT_SECRET: test_secret_key
      JWT_EXPIRES_IN: 1d
    ports:
      - '3001:3001'
    depends_on:
      postgres_test:
        condition: service_healthy
    command: pnpm test

volumes:
  postgres_test_data:
    name: my_new_gear_postgres_test_data
